services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms1g -Xmx1g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
      xpack.security.enabled: false
      xpack.fleet.agents.enabled: false
      xpack.fleet.isAirGapped: false
    ports:
      - "5601:5601"
    depends_on:
      - elastic